export const STEPS = {
  MAIN_MENU: "MAIN_MENU",
  REFRIGERACION_MENU: "REFRIGERACION_MENU",
  AIRE_MENU: "AIRE_MENU",
  VEHICULOS_MENU: "VEHICULOS_MENU",
  CONTACTING_ADVISOR: "CONTACTING_ADVISOR",
};